# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

load_block_file <- function(block_file) {
    .Call(`_MR_CUE_load_block_file`, block_file)
}

test_blocks <- function(bp, chr, block_file) {
    .Call(`_MR_CUE_test_blocks`, bp, chr, block_file)
}

std_setdiff <- function(x, y) {
    .Call(`_MR_CUE_std_setdiff`, x, y)
}

LDclump <- function(R, ld_r2_thresh) {
    .Call(`_MR_CUE_LDclump`, R, ld_r2_thresh)
}

Cal_blockR <- function(bp, chr, avbIndex, idx4panel, block_file, stringname3, ld_r2_thresh, coreNum, lam) {
    .Call(`_MR_CUE_Cal_blockR`, bp, chr, avbIndex, idx4panel, block_file, stringname3, ld_r2_thresh, coreNum, lam)
}

Cal_block_Rmatrix <- function(bp, chr, avbIndex, idx4panel, block_file, stringname3, ld_r2_thresh, coreNum, lam) {
    .Call(`_MR_CUE_Cal_block_Rmatrix`, bp, chr, avbIndex, idx4panel, block_file, stringname3, ld_r2_thresh, coreNum, lam)
}

Cal_blockinf <- function(bp, chr, block_file) {
    .Call(`_MR_CUE_Cal_blockinf`, bp, chr, block_file)
}

IndepSummary <- function(bp, chr, avbIndex, block_file, stringname3, bh1, bh2, se1, se2, coreNum, lam, ld_r2_thresh) {
    .Call(`_MR_CUE_IndepSummary`, bp, chr, avbIndex, block_file, stringname3, bh1, bh2, se1, se2, coreNum, lam, ld_r2_thresh)
}

testR <- function(rho, n) {
    .Call(`_MR_CUE_testR`, rho, n)
}

comb <- function(p) {
    .Call(`_MR_CUE_comb`, p)
}

Mat2Vec <- function(R) {
    .Call(`_MR_CUE_Mat2Vec`, R)
}

Vec2Mat <- function(RV, p1) {
    .Call(`_MR_CUE_Vec2Mat`, RV, p1)
}

Cal_block_Rvec <- function(bp, chr, avbIndex, block_file, stringname3, coreNum, lam) {
    .Call(`_MR_CUE_Cal_block_Rvec`, bp, chr, avbIndex, block_file, stringname3, coreNum, lam)
}

MRCUEIndep <- function(gammah, Gammah, se1, se2, rho, opts = NULL) {
    .Call(`_MR_CUE_MRCUEIndep`, gammah, Gammah, se1, se2, rho, opts)
}

MRCUESim <- function(gammah, Gammah, se1, se2, rho, R, block_inf, coreNum, opts = NULL) {
    .Call(`_MR_CUE_MRCUESim`, gammah, Gammah, se1, se2, rho, R, block_inf, coreNum, opts)
}

MRCUE <- function(F4gammah, F4Gammah, F4se1, F4se2, F4Rblock, rho, coreNum, opts = NULL) {
    .Call(`_MR_CUE_MRCUE`, F4gammah, F4Gammah, F4se1, F4se2, F4Rblock, rho, coreNum, opts)
}

getLineNum <- function(filename) {
    .Call(`_MR_CUE_getLineNum`, filename)
}

ReadSNPinfo <- function(stringname, A1, A2, rsname, chr, bp, morgan, N) {
    .Call(`_MR_CUE_ReadSNPinfo`, stringname, A1, A2, rsname, chr, bp, morgan, N)
}

Read_summarystat <- function(stringname, SA1, SA2, rsname, betah, s2, pvalue, chr, bp, N) {
    invisible(.Call(`_MR_CUE_Read_summarystat`, stringname, SA1, SA2, rsname, betah, s2, pvalue, chr, bp, N))
}

select <- function(vec_, idx_) {
    .Call(`_MR_CUE_select`, vec_, idx_)
}

matchsnp <- function(stringname1, stringname2, stringname3, matchExp) {
    .Call(`_MR_CUE_matchsnp`, stringname1, stringname2, stringname3, matchExp)
}

matchscreen <- function(screenname, stringname1, stringname2, stringname3, pva_cutoff, matchExp = FALSE) {
    .Call(`_MR_CUE_matchscreen`, screenname, stringname1, stringname2, stringname3, pva_cutoff, matchExp)
}

Cal_block_SimR <- function(block_inf, X, lam) {
    .Call(`_MR_CUE_Cal_block_SimR`, block_inf, X, lam)
}

fastSigLm <- function(y, X) {
    .Call(`_MR_CUE_fastSigLm`, y, X)
}

normal_pdf <- function(x, m, s) {
    .Call(`_MR_CUE_normal_pdf`, x, m, s)
}

phi <- function(x) {
    .Call(`_MR_CUE_phi`, x)
}

cdfNormal <- function(x, mean, sd) {
    .Call(`_MR_CUE_cdfNormal`, x, mean, sd)
}

MulticdfNormal <- function(x) {
    .Call(`_MR_CUE_MulticdfNormal`, x)
}

multiphi <- function(x) {
    .Call(`_MR_CUE_multiphi`, x)
}

inverseNormal <- function(prob, mean, sd) {
    .Call(`_MR_CUE_inverseNormal`, prob, mean, sd)
}

MultiinverseNormal <- function(prob) {
    .Call(`_MR_CUE_MultiinverseNormal`, prob)
}

MatSum <- function(y1, y2) {
    .Call(`_MR_CUE_MatSum`, y1, y2)
}

truncEstfun <- function(a, b, x1, x2, maxIter, burnin, thin) {
    .Call(`_MR_CUE_truncEstfun`, a, b, x1, x2, maxIter, burnin, thin)
}

